/**
 * String helpers shared by slugs, SEO and every label the UI renders.
 *
 * The two tables below — the transliteration map and the English stop-word
 * list — are ported from Front Matter CMS (MIT) so that slugs generated by
 * this extension match the ones already committed in repositories that used
 * it. They are data, not logic: grouped here by their replacement to keep 266
 * mappings readable.
 *
 * `slugify` keeps FM's pipeline — remove punctuation, lowercase, drop stop
 * words, join with `-`, transliterate — but *which* words it drops is now a
 * project setting rather than a constant. FM's list is the SMART information-
 * retrieval stop-word list, built for matching documents, and it deletes words
 * a title needs: `back`, `new`, `value`, `use`, `way`, `thing`, `second`,
 * `vs`, and — worst — `without`. Measured over a real 72-post site, 31% of
 * titles lost a word that carried meaning:
 *
 *     "MCP for the back office"                  → mcp-office
 *     "From prompts to pipelines: AI in VS Code" → prompts-pipelines-ai-code
 *     "… to QAD Enterprise without losing data"  → …-enterprise-losing-data
 *
 * The last one is not a shorter URL, it is the opposite claim. So `MINIMAL`
 * is the default and `SMART` is one setting away for a repository whose
 * permalinks were already minted by Front Matter. See `SlugConfig.stopWords`.
 */

/** Transliteration source, grouped by replacement. */
const CHAR_TABLE: ReadonlyArray<readonly [string, string]> = [
  // latin
  ['A', 'ÀÁÂÃÄÅ'],
  ['AE', 'Æ'],
  ['C', 'Ç'],
  ['E', 'ÈÉÊË'],
  ['I', 'ÌÍÎÏ'],
  ['D', 'Ð'],
  ['N', 'Ñ'],
  ['O', 'ÒÓÔÕÖŐØ'],
  ['U', 'ÙÚÛÜŰ'],
  ['Y', 'Ý'],
  ['TH', 'Þ'],
  ['ss', 'ß'],
  ['a', 'àáâãäå'],
  ['ae', 'æ'],
  ['c', 'ç'],
  ['e', 'èéêë'],
  ['i', 'ìíîï'],
  ['d', 'ð'],
  ['n', 'ñ'],
  ['o', 'òóôõöőø'],
  ['u', 'ùúûüű'],
  ['y', 'ýÿ'],
  ['th', 'þ'],
  ['SS', 'ẞ'],
  // greek
  ['a', 'αά'],
  ['b', 'β'],
  ['g', 'γ'],
  ['d', 'δ'],
  ['e', 'εέ'],
  ['z', 'ζ'],
  ['h', 'ηή'],
  ['8', 'θΘ'],
  ['i', 'ιίϊΐ'],
  ['k', 'κ'],
  ['l', 'λ'],
  ['m', 'μ'],
  ['n', 'ν'],
  ['3', 'ξΞ'],
  ['o', 'οό'],
  ['p', 'π'],
  ['r', 'ρ'],
  ['s', 'σς'],
  ['t', 'τ'],
  ['y', 'υύΰϋ'],
  ['f', 'φ'],
  ['x', 'χ'],
  ['ps', 'ψ'],
  ['w', 'ωώ'],
  ['A', 'ΑΆ'],
  ['B', 'Β'],
  ['G', 'Γ'],
  ['D', 'Δ'],
  ['E', 'ΕΈ'],
  ['Z', 'Ζ'],
  ['H', 'ΗΉ'],
  ['I', 'ΙΊΪ'],
  ['K', 'Κ'],
  ['L', 'Λ'],
  ['M', 'Μ'],
  ['N', 'Ν'],
  ['O', 'ΟΌ'],
  ['P', 'Π'],
  ['R', 'Ρ'],
  ['S', 'Σ'],
  ['T', 'Τ'],
  ['Y', 'ΥΎΫ'],
  ['F', 'Φ'],
  ['X', 'Χ'],
  ['PS', 'Ψ'],
  ['W', 'ΩΏ'],
  // turkish
  ['s', 'ş'],
  ['S', 'Ş'],
  ['i', 'ı'],
  ['I', 'İ'],
  ['g', 'ğ'],
  ['G', 'Ğ'],
  // russian
  ['a', 'а'],
  ['b', 'б'],
  ['v', 'в'],
  ['g', 'г'],
  ['d', 'д'],
  ['e', 'еэ'],
  ['yo', 'ё'],
  ['zh', 'ж'],
  ['z', 'з'],
  ['i', 'и'],
  ['j', 'й'],
  ['k', 'к'],
  ['l', 'л'],
  ['m', 'м'],
  ['n', 'н'],
  ['o', 'о'],
  ['p', 'п'],
  ['r', 'р'],
  ['s', 'с'],
  ['t', 'т'],
  ['u', 'уъ'],
  ['f', 'ф'],
  ['h', 'х'],
  ['c', 'ц'],
  ['ch', 'ч'],
  ['sh', 'шщ'],
  ['y', 'ы'],
  ['', 'ьЬ'],
  ['yu', 'ю'],
  ['ya', 'я'],
  ['A', 'А'],
  ['B', 'Б'],
  ['V', 'В'],
  ['G', 'Г'],
  ['D', 'Д'],
  ['E', 'ЕЭ'],
  ['Yo', 'Ё'],
  ['Zh', 'Ж'],
  ['Z', 'З'],
  ['I', 'И'],
  ['J', 'Й'],
  ['K', 'К'],
  ['L', 'Л'],
  ['M', 'М'],
  ['N', 'Н'],
  ['O', 'О'],
  ['P', 'П'],
  ['R', 'Р'],
  ['S', 'С'],
  ['T', 'Т'],
  ['U', 'УЪ'],
  ['F', 'Ф'],
  ['H', 'Х'],
  ['C', 'Ц'],
  ['Ch', 'Ч'],
  ['Sh', 'ШЩ'],
  ['Y', 'Ы'],
  ['Yu', 'Ю'],
  ['Ya', 'Я'],
  // ukranian
  ['Ye', 'Є'],
  ['I', 'І'],
  ['Yi', 'Ї'],
  ['G', 'Ґ'],
  ['ye', 'є'],
  ['i', 'і'],
  ['yi', 'ї'],
  ['g', 'ґ'],
  // czech
  ['c', 'č'],
  ['d', 'ď'],
  ['e', 'ě'],
  ['n', 'ň'],
  ['r', 'ř'],
  ['s', 'š'],
  ['t', 'ť'],
  ['u', 'ů'],
  ['z', 'ž'],
  ['C', 'Č'],
  ['D', 'Ď'],
  ['E', 'Ě'],
  ['N', 'Ň'],
  ['R', 'Ř'],
  ['S', 'Š'],
  ['T', 'Ť'],
  ['U', 'Ů'],
  ['Z', 'Ž'],
  // polish
  ['a', 'ą'],
  ['c', 'ć'],
  ['e', 'ęĘ'],
  ['l', 'ł'],
  ['n', 'ń'],
  ['s', 'ś'],
  ['z', 'źż'],
  ['A', 'Ą'],
  ['C', 'Ć'],
  ['L', 'Ł'],
  ['N', 'Ń'],
  ['S', 'Ś'],
  ['Z', 'ŹŻ'],
  // latvian
  ['a', 'ā'],
  ['e', 'ē'],
  ['g', 'ģ'],
  ['i', 'īĪ'],
  ['k', 'ķĶ'],
  ['l', 'ļ'],
  ['n', 'ņ'],
  ['u', 'ūŪ'],
  ['A', 'Ā'],
  ['E', 'Ē'],
  ['G', 'Ģ'],
  ['L', 'Ļ'],
  ['N', 'Ņ'],
];

/** Single character → ASCII replacement. Later groups win, as in the source. */
export const CHAR_MAP: Readonly<Record<string, string>> = (() => {
  const map: Record<string, string> = {};
  for (const [replacement, sources] of CHAR_TABLE) {
    for (const ch of sources) {
      map[ch] = replacement;
    }
  }
  return map;
})();

/**
 * English stop words dropped from generated slugs. Kept as one string because
 * a 659-element array literal is 659 lines of noise; several entries contain
 * apostrophes (`ain't`, `a's`), which is why the delimiter is whitespace.
 */
const STOP_WORD_SOURCE = `
a able about above abroad according accordingly across actually adj after afterwards again
against ago ahead ain't all allow allows almost alone along alongside already also although
always am amid amidst among amongst an and another any anybody anyhow anyone anything anyway
anyways anywhere apart appear appreciate appropriate are aren't around as a's aside ask asking
associated at available away awfully b back backward backwards be became because become becomes
becoming been before beforehand begin behind being believe below beside besides best better
between beyond both brief but by c came can cannot cant can't caption cause causes certain
certainly changes clearly c'mon co co. com come comes concerning consequently consider
considering contain containing contains corresponding could couldn't course c's currently d
dare daren't definitely described despite did didn't different directly do does doesn't doing
done don't down downwards during e each edu eg eight eighty either else elsewhere end ending
enough entirely especially et etc even ever evermore every everybody everyone everything
everywhere ex exactly example except f fairly far farther few fewer fifth first five followed
following follows for forever former formerly forth forward found four from further furthermore
g get gets getting given gives go goes going gone got gotten greetings h had hadn't half
happens hardly has hasn't have haven't having he he'd he'll hello help hence her here hereafter
hereby herein here's hereupon hers herself he's hi him himself his hither hopefully how howbeit
however hundred i i'd ie if ignored i'll i'm immediate in inasmuch inc inc. indeed indicate
indicated indicates inner inside insofar instead into inward is isn't it it'd it'll its it's
itself i've j just k keep keeps kept know known knows l last lately later latter latterly least
less lest let let's like liked likely likewise little look looking looks low lower ltd m made
mainly make makes many may maybe mayn't me mean meantime meanwhile merely might mightn't mine
minus miss more moreover most mostly mr mrs much must mustn't my myself n name namely nd near
nearly necessary need needn't needs neither never neverf neverless nevertheless new next nine
ninety no nobody non none nonetheless noone no-one nor normally not nothing notwithstanding
novel now nowhere o obviously of off often oh ok okay old on once one ones one's only onto
opposite or other others otherwise ought oughtn't our ours ourselves out outside over overall
own p particular particularly past per perhaps placed please plus possible presumably probably
provided provides q que quite qv r rather rd re really reasonably recent recently regarding
regardless regards relatively respectively right round s said same saw say saying says second
secondly see seeing seem seemed seeming seems seen self selves sensible sent serious seriously
seven several shall shan't she she'd she'll she's should shouldn't since six so some somebody
someday somehow someone something sometime sometimes somewhat somewhere soon sorry specified
specify specifying still sub such sup sure t take taken taking tell tends th than thank thanks
thanx that that'll thats that's that've the their theirs them themselves then thence there
thereafter thereby there'd therefore therein there'll there're theres there's thereupon
there've these they they'd they'll they're they've thing things think third thirty this
thorough thoroughly those though three through throughout thru thus till to together too took
toward towards tried tries truly try trying t's twice two u un under underneath undoing
unfortunately unless unlike unlikely until unto up upon upwards us use used useful uses using
usually v value various versus very via viz vs w want wants was wasn't way we we'd welcome well
we'll went were we're weren't we've what whatever what'll what's what've when whence whenever
where whereafter whereas whereby wherein where's whereupon wherever whether which whichever
while whilst whither who who'd whoever whole who'll whom whomever who's whose why will willing
wish with within without wonder won't would wouldn't x y yes yet you you'd you'll your you're
yours yourself yourselves you've z zero
`;

/**
 * Front Matter's list, unchanged. Kept so a repository whose permalinks were
 * minted by FM can go on minting the same ones: `"slug": {"stopWords":
 * "smart"}`.
 */
export const STOP_WORDS: ReadonlySet<string> = new Set(STOP_WORD_SOURCE.trim().split(/\s+/));

/**
 * The default: the closed class of English function words that carry no
 * meaning of their own — articles, coordinating conjunctions, and the
 * prepositions common enough to be noise in a URL.
 *
 * Every word here is one whose removal a reader would not notice. `without`
 * is deliberately absent even though `with` is present: it negates, and a
 * slug that drops a negation states the opposite of its title.
 */
export const MINIMAL_STOP_WORDS: ReadonlySet<string> = new Set(
  'a an the and or of to in on for with at by from'.split(' '),
);

/** No removal at all — every word survives into the slug. */
export const NO_STOP_WORDS: ReadonlySet<string> = new Set<string>();

/** The named lists `slug.stopWords` accepts, besides a literal array. */
export const STOP_WORD_PRESETS: Readonly<Record<string, ReadonlySet<string>>> = {
  smart: STOP_WORDS,
  minimal: MINIMAL_STOP_WORDS,
  none: NO_STOP_WORDS,
};

/**
 * Replace punctuation with spaces and collapse runs of whitespace.
 * The character class is FM's, verbatim: `,-/` is a range covering `, - . /`.
 */
export function removePunctuation(value: string): string {
  if (typeof value !== 'string') {
    return '';
  }
  return value.replace(/[.,\-/#!$@%^&*;:{}=_`'"~()+?<>]/g, ' ').replace(/\s{2,}/g, ' ');
}

/** Drop stop words, comparing case-insensitively. */
export function removeStopWords(
  words: readonly string[],
  stopWords: ReadonlySet<string> = MINIMAL_STOP_WORDS,
): string[] {
  return words.filter((word) => word !== '' && !stopWords.has(word.toLowerCase()));
}

/** Map accented and non-Latin characters onto their ASCII stand-ins. */
export function transliterate(value: string): string {
  let out = '';
  for (const ch of value) {
    out += CHAR_MAP[ch] ?? ch;
  }
  return out;
}

/**
 * `"The Quick, Brown Fox"` → `"quick-brown-fox"`.
 *
 * `stopWords` defaults to `MINIMAL_STOP_WORDS` rather than taking the value
 * from a config object, because this module is the bottom of the stack and
 * knows nothing about `Zer0Config`. Callers that have one pass
 * `cfg.slug.stopWords`; `createSlug` and `publish` both do.
 *
 * The trailing collapse of repeated and edge dashes is the one addition to
 * FM's pipeline: it only fires on input where FM produced `--` or a leading
 * `-`, which was never a slug anybody wanted.
 */
export function slugify(value: string, stopWords: ReadonlySet<string> = MINIMAL_STOP_WORDS): string {
  const clean = removePunctuation(value).trim();
  if (!clean) {
    return '';
  }
  const words = removeStopWords(clean.toLowerCase().split(/\s/), stopWords);
  return transliterate(words.join('-'))
    .replace(/-{2,}/g, '-')
    .replace(/^-+|-+$/g, '');
}

const PICTOGRAPHIC = /\p{Extended_Pictographic}/u;

/**
 * Encode emoji as `\uXXXX` escapes, for front-matter dialects (and downstream
 * pipelines) that cannot carry them literally. Opt-in per field.
 */
export function encodeEmoji(text: string): string {
  if (!text || !PICTOGRAPHIC.test(text)) {
    return text;
  }
  return [...text]
    .map((ch) =>
      PICTOGRAPHIC.test(ch) ? `\\u${(ch.codePointAt(0) ?? 0).toString(16).toUpperCase()}` : ch,
    )
    .join('');
}

/** `"hello world"` → `"Hello World"`. Used for field labels, never for content. */
export function titleCase(value: string): string {
  return value
    .split(/(\s+)/)
    .map((part) => (/\s/.test(part) ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join('');
}

/** `"my-field_name"` → `"My field name"` — a readable label from a key. */
export function humanize(value: string): string {
  return titleCase(value.replace(/[_-]+/g, ' ').replace(/\s{2,}/g, ' ').trim());
}

/** Shorten to `max` characters, appending `suffix` when anything was cut. */
export function truncate(value: string, max: number, suffix = '…'): string {
  if (max <= 0 || value.length <= max) {
    return value;
  }
  const keep = Math.max(0, max - suffix.length);
  return value.slice(0, keep).trimEnd() + suffix;
}

/**
 * Escape for HTML text and attribute contexts. The webviews build DOM with
 * `el()`/`textContent` and never interpolate markup, so this exists for the
 * few places that emit markdown/HTML fragments to disk (previews, worklists).
 */
export function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/** Collapse all whitespace runs to single spaces and trim. */
export function collapseWhitespace(value: string): string {
  return value.replace(/\s+/g, ' ').trim();
}
