/**
 * The catering worklist, rendered byte-for-byte in the engine's own format.
 *
 * This is a port of the Python lane's `catering.render()`, and "port" here
 * means *identical output*: same headings, same table columns, same empty
 * states, same prose. The golden test compares this function's result against
 * a file the Python implementation wrote, so a reader who opens
 * `.cms/distribution/worklists/` cannot tell which lane produced which file —
 * which is the entire point of having two lanes.
 *
 * That is also why the number formatters are hand-rolled. `toLocaleString`
 * would produce `1 234` or `1.234` depending on the machine's locale, and a
 * worklist that changes when you fly to Berlin is not a contract.
 *
 * If you need to change the wording, change it in the Python lane, regenerate
 * the golden fixture, and copy it here — not the other way round.
 *
 * ## The prose has one mirror, and it is deliberate
 *
 * `src/webview/dashboard/catering.ts` restates the lane hints (`HINTS`), the
 * empty states (`EMPTY_STATES`) and both number formatters (`formatThousands`,
 * `formatPercent`) because this module imports `../contract/contract`, which
 * imports `node:fs`: a browser bundle cannot reach it at all. Everything
 * host-side imports `LANE_EMPTY_STATES` from here instead of copying it, so the
 * screen and the generated file cannot drift. If you edit a sentence or a
 * formatter in this file, edit its twin in `catering.ts` in the same commit —
 * a lane that reads `1 234` on screen and `1,234` in the file is the bug the
 * hand-rolled formatters exist to prevent.
 */

import { writeWorklist, type Contract } from '../contract/contract';
import { MIN_OBSERVATIONS, hasEvidence, rateOf, type CateringPlan } from './catering';

/**
 * The five italic empty-state sentences, without their markdown underscores.
 *
 * `renderWorklist` wraps each one in `_…_`; `src/dashboard/dashboardPanel.ts`
 * sends them to the dashboard as `CateringState.emptyStates`. One definition,
 * two renderings — the screen and `.cms/distribution/worklists/<date>.md` say
 * the same thing about an empty lane because they read the same string.
 *
 * Changing any of these changes the golden fixture. Regenerate it from the
 * Python lane; never hand-edit one to match a change made here.
 */
export const LANE_EMPTY_STATES = {
  undistributed: 'Everything publishable has been distributed.',
  /** Lane B when no post has statistics read back yet. */
  provenNoEvidence:
    'No audience data yet. Topic rankings need published posts with statistics read back; ' +
    'until then this lane is empty rather than guessed.',
  /** Lane B when there is data but no topic clears the observation floor. */
  provenThin:
    `Not enough observations yet — a topic needs ${MIN_OBSERVATIONS} posts before its average ` +
    'means anything.',
  quiet: 'Nothing to report.',
  refresh: 'Nothing published has gone stale.',
} as const;

/** Python's `{:,}` thousands separator. Deterministic — no locale involved. */
export function formatThousands(n: number): string {
  return n.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',');
}

/** Python's `{:.2%}` — rate × 100, two decimals, half-to-even rounding. */
export function formatPercent(rate: number): string {
  const hundredths = rate * 10000; // percent, scaled to two decimals
  const floor = Math.floor(hundredths);
  const diff = hundredths - floor;
  const eps = 1e-9;
  const cents =
    Math.abs(diff - 0.5) < eps ? (floor % 2 === 0 ? floor : floor + 1) : Math.round(hundredths);
  return `${(cents / 100).toFixed(2)}%`;
}

/** Health column: the score, or an em dash when the engine never scored it. */
function healthCell(health: number): string {
  return health >= 0 ? String(health) : '—';
}

export function renderWorklist(plan: CateringPlan, date: string): string {
  const lines: string[] = [
    `# Distribution worklist — ${date}`,
    '',
    '_Generated by `zer0-distribute cater`. The audience-evidence counterpart to ' +
      '`.cms/worklists/<date>.md`: that one says what is wrong with the content, this one ' +
      "says what to write next. Rankings use the author's own aggregate post statistics; " +
      'no member-level data is read or stored._',
    '',
  ];

  lines.push('## Lane A — Distribute what already exists', '');
  if (plan.undistributed.length) {
    lines.push(
      'Content that scores well and has never been published off-site. No writing ' +
        'required, so this is the cheapest work on the list.',
      '',
      '| # | Health | Fresh | Collection | File |',
      '|---|---|---|---|---|',
    );
    plan.undistributed.forEach((record, idx) => {
      lines.push(
        `| ${idx + 1} | ${healthCell(record.health)} | ${record.freshness} | ` +
          `${record.collection} | \`${record.path}\` |`,
      );
    });
  } else {
    lines.push(`_${LANE_EMPTY_STATES.undistributed}_`);
  }
  lines.push('');

  lines.push('## Lane B — Write more of what landed', '');
  if (!hasEvidence(plan)) {
    lines.push(`_${LANE_EMPTY_STATES.provenNoEvidence}_`, '');
  } else if (plan.proven.length) {
    lines.push(
      'Topics at or above the median engagement rate, each with at least ' +
        `${MIN_OBSERVATIONS} posts behind it. Evidence, not a guarantee.`,
      '',
      '| Topic | Posts | Impressions | Engagement rate |',
      '|---|---|---|---|',
    );
    for (const signal of plan.proven) {
      lines.push(
        `| ${signal.topic} | ${signal.posts} | ${formatThousands(signal.impressions)} | ` +
          `${formatPercent(rateOf(signal))} |`,
      );
    }
    lines.push('');
  } else {
    lines.push(`_${LANE_EMPTY_STATES.provenThin}_`, '');
  }

  lines.push('## Lane C — Say the quiet part', '');
  if (plan.quiet.length) {
    lines.push(
      'Topics below the median. Worth naming, because the alternative is repeating ' +
        'them by default. Low engagement is not the same as low value — a compliance ' +
        'post can matter and still be unpopular.',
      '',
      '| Topic | Posts | Impressions | Engagement rate |',
      '|---|---|---|---|',
    );
    for (const signal of plan.quiet) {
      lines.push(
        `| ${signal.topic} | ${signal.posts} | ${formatThousands(signal.impressions)} | ` +
          `${formatPercent(rateOf(signal))} |`,
      );
    }
  } else {
    lines.push(`_${LANE_EMPTY_STATES.quiet}_`);
  }
  lines.push('');

  lines.push('## Lane D — Refresh what worked', '');
  if (plan.refresh.length) {
    lines.push(
      'Content that earned engagement and has since gone stale. Updating a page that ' +
        'already found its readers beats starting from nothing.',
      '',
      '| Health | Fresh | File |',
      '|---|---|---|',
    );
    for (const record of plan.refresh) {
      lines.push(`| ${healthCell(record.health)} | ${record.freshness} | \`${record.path}\` |`);
    }
  } else {
    lines.push(`_${LANE_EMPTY_STATES.refresh}_`);
  }
  lines.push('');

  return lines.join('\n');
}

/** Render and write in one step; returns the absolute path written. */
export async function writeCateringWorklist(
  contract: Contract,
  plan: CateringPlan,
  date: string,
): Promise<string> {
  return writeWorklist(contract, date, renderWorklist(plan, date));
}
