# frozen_string_literal: true

require "minitest/autorun"
require "fileutils"
require "json"
require "tmpdir"
require_relative "../../lib/zer0_cms/cms/catalog"

# The expected lists under test/fixtures/*.expected.json were generated by
# `ruby bin/jekyll-parity <fixture> --json` with Jekyll 4.4.1 — Jekyll's own
# reader, not a hand-written expectation. Regenerate them the same way.
class TestCatalogJekyllParity < Minitest::Test
  FIXTURES = File.expand_path("../fixtures", __dir__)
  COUNTED = %i[non_content_pages non_content_posts non_content_documents].freeze

  def assert_matches_jekyll(name)
    expected = JSON.parse(File.read(File.join(FIXTURES, "#{name}.expected.json")))
    result = Zer0Cms::Cms::Catalog.scan(File.join(FIXTURES, name))
    assert_equal expected["entries"], result.entries.map { |e| [e.collection, e.source_relative] }.sort, name
    assert_equal expected["skipped"], COUNTED.to_h { |k| [k.to_s, result.skipped[k]] }, name
  end

  def test_fixture_site_matches_jekyll
    assert_matches_jekyll("jekyll-site")
  end

  def test_source_subdirectory_fixture_matches_jekyll
    assert_matches_jekyll("jekyll-site-src")
  end

  def test_fixture_details
    result = Zer0Cms::Cms::Catalog.scan(File.join(FIXTURES, "jekyll-site"), now: Time.utc(2026, 9, 14))
    by_path = result.entries.to_h { |e| [e.source_relative, e] }
    assert_equal :draft, by_path["pages/_drafts/wip.md"].kind
    assert by_path["pages/_posts/2099-01-01-future.md"].future
    refute by_path["pages/_docs/hidden.md"].published
    assert_nil by_path["guides/template.md"].date, "a {{date}} placeholder is not a date"
    assert_nil by_path["guides/template.md"].error
    assert_equal "Hello", by_path["pages/_posts/2026-01-01-hello.md"].title
    assert_equal "No Front Matter", by_path["pages/_posts/2026-02-02-no-front-matter.md"].title
    refute by_path["pages/_posts/2026-02-02-no-front-matter.md"].front_matter
    assert_equal 1, result.skipped[:undated_posts]
    assert_equal %w[posts docs notes], result.collections
  end
end

class TestCatalogHardening < Minitest::Test
  Catalog = Zer0Cms::Cms::Catalog

  def site(config)
    Dir.mktmpdir do |dir|
      File.write(File.join(dir, "_config.yml"), config)
      yield dir
    end
  end

  def write(dir, rel, text = "---\ntitle: T\n---\nBody\n")
    path = File.join(dir, rel)
    FileUtils.mkdir_p(File.dirname(path))
    File.write(path, text)
    path
  end

  def test_scan_reads_post_front_matter
    site("title: t\ncollections_dir: pages\n") do |dir|
      write(dir, "pages/_posts/2026-01-01-hello.md", "---\ntitle: Hello\nauthor: rhea\ncategories: [Hacks]\ntags: [ci]\ndraft: false\n---\nBody\n")
      entry = Catalog.scan(dir).entries.first
      assert_equal ["Hello", "rhea", ["Hacks"], ["ci"], false], [entry.title, entry.author, entry.categories, entry.tags, entry.draft]
    end
  end

  def test_front_matter_errors_are_recorded_not_raised
    site("title: t\n") do |dir|
      write(dir, "broken.md", "---\ntitle: [x\n---\nBody\n")
      entry = Catalog.scan(dir).entries.first
      assert_match(/\Afront matter: /, entry.error)
      assert_equal({}, entry.data)
    end
  end

  def test_refuses_a_source_outside_the_root
    ["source: ..\n", "source: /etc\n", "source: sub/../../elsewhere\n"].each do |config|
      site(config) do |dir|
        assert_raises(Zer0Cms::Cms::UnsafePath, config) { Catalog.scan(dir) }
      end
    end
  end

  def test_refuses_a_collections_dir_outside_the_root
    ["collections_dir: ../x\n", "collections_dir: /tmp\n"].each do |config|
      site(config) do |dir|
        assert_raises(Zer0Cms::Cms::UnsafePath, config) { Catalog.scan(dir) }
      end
    end
  end

  def test_refuses_a_source_symlinked_outside_the_root
    Dir.mktmpdir do |outside|
      site("source: src\n") do |dir|
        File.symlink(outside, File.join(dir, "src"))
        assert_raises(Zer0Cms::Cms::UnsafePath) { Catalog.scan(dir) }
      end
    end
  end

  def test_symlinked_entries_are_skipped_and_counted
    Dir.mktmpdir do |outside|
      secret = write(outside, "secret.md", "---\ntitle: Secret\n---\n")
      site("collections_dir: pages\ncollections:\n  docs: {}\n") do |dir|
        write(dir, "pages/_docs/real.md")
        File.symlink(secret, File.join(dir, "pages/_docs/linked.md"))
        File.symlink(secret, File.join(dir, "linked-page.md"))
        FileUtils.mkdir_p(File.join(dir, "pages/_posts"))
        File.symlink(secret, File.join(dir, "pages/_posts/2026-01-01-linked.md"))
        File.symlink(outside, File.join(dir, "linked-dir"))
        result = Catalog.scan(dir)
        assert_equal ["pages/_docs/real.md"], result.entries.map(&:source_relative)
        assert_equal 4, result.skipped[:symlinks]
      end
    end
  end

  def test_legacy_list_form_collections
    site("collections: [recipes, \"bad/../name\"]\n") do |dir|
      write(dir, "_recipes/soup.md")
      result = Catalog.scan(dir)
      # Jekyll's label sanitising drops the slashes and keeps the dots.
      assert_equal %w[posts recipes bad..name], result.collections
      assert_equal [["recipes", "_recipes/soup.md"]], result.entries.map { |e| [e.collection, e.source_relative] }
    end
  end

  def test_a_configured_include_replaces_the_htaccess_default
    site("include: [_kept.md]\n") do |dir|
      write(dir, ".htaccess.md")
      write(dir, "_kept.md")
      assert_equal ["_kept.md"], Catalog.scan(dir).entries.map(&:source_relative)
    end
    site("title: t\n") do |dir|
      assert_equal [".htaccess"], Catalog.site_for(dir).includes
    end
  end

  def test_invalid_utf8_posts_are_skipped_like_jekyll
    site("title: t\n") do |dir|
      write(dir, "_posts/2026-01-01-bad.md", "---\ntitle: T\n---\n\xFF\n".b)
      write(dir, "bad-page.md", "---\ntitle: T\n---\n\xFF\n".b)
      result = Catalog.scan(dir)
      assert_equal ["bad-page.md"], result.entries.map(&:source_relative)
      assert_equal 1, result.skipped[:invalid_utf8_posts]
      assert_equal "not valid UTF-8", result.entries.first.error
    end
  end

  def test_media_ignores_an_output_dir_outside_the_root
    Dir.mktmpdir do |outside|
      File.write(File.join(outside, "leak.png"), "x")
      site("preview_images:\n  output_dir: #{outside}\n") do |dir|
        write(dir, "assets/images/ok.png", "x")
        assert_equal [File.realpath(File.join(dir, "assets/images/ok.png"))], Catalog.media(dir).map(&:to_s)
      end
    end
  end
end
