/**
 * `harness-registry/v1` — the hub's daily census of every repository's AI
 * harness, read tolerantly and only as far as the hub promises it is stable.
 *
 * The file is `bamr87/bamr87` `_data/harness_registry.yml`, generated by
 * `.github/scripts/dash-gen` and refreshed by `fleet-pulse.yml`. It is 3,600
 * lines of a generator's output and it grows: the hub's `docs/HARNESS-OPS.md`
 * declares which fields consumers may depend on, and says additive changes are
 * free. So this reader takes exactly those fields and nothing else — a new key
 * appearing upstream must never be a parse error here, and a key this reader has
 * never heard of must never reach a caller as though it were a contract.
 *
 * The one refusal is the `schema:` marker, for the same reason `manifest.ts`
 * refuses a foreign `spec_version`: rendering a table off a document written to
 * a different contract is how a console tells a confident lie. A refusal comes
 * back as `{ refused }` — a value, never a throw (decision D9: an absent or
 * unreadable file is a normal state).
 *
 * Parsing goes through `parseYamlSubset`, the hand-rolled reader, not the `yaml`
 * package: this module is barrel-exported and therefore lives in the MCP
 * server's import graph, where no bare import is allowed at all (D14).
 *
 * ## The blind spot, carried as data
 *
 * The hub's generator counts a workflow as "AI" only when the file contains
 * `anthropics/claude-code-action`. Every other way the fleet calls a model —
 * the hub's own `claude-run` composite, a vendored `scripts/ai/run.sh`, a bare
 * `claude` CLI, an agentic engine driver, a caller of the reusable `ai-lane.yml`
 * — is invisible to it. The gap is not small: lifehacker.dev's registry entry
 * lists **3** harnesses while its committed `fleet.manifest.yml` declares **17**
 * lanes, all of which cost money. So `blindSpotNote` travels with the data and
 * the console renders it beside any count taken from this file. A number without
 * its blind spot is worse than no number.
 */

import { parseYamlSubset } from '../content/frontmatter';

/** The one registry schema this reader speaks. */
export const HARNESS_REGISTRY_SCHEMA = 'harness-registry/v1';

/**
 * What `docs/HARNESS-OPS.md` names stable, said once so the test and the reader
 * cannot drift apart. Anything not on this list is deliberately dropped.
 */
export const REGISTRY_STABLE_REPO_FIELDS: readonly string[] = [
  'repo',
  'nwo',
  'category',
  'status',
  'archived',
  'scanned',
  'manifest',
  'factory',
  'agentContext',
  'oauthSecret',
  'workflowsTotal',
  'harnesses',
  'aiUsage',
  'coverageOk',
  'coverageMissing',
];

/** The sentence every count taken from this file is shown next to. */
export const HARNESS_REGISTRY_BLIND_SPOT =
  "The hub's generator counts a workflow as AI only when it contains `anthropics/claude-code-action`. " +
  'Lanes that call a model any other way — the hub `claude-run` composite, a vendored run.sh, a bare CLI, ' +
  'an agentic engine, a caller of the reusable ai-lane.yml — are invisible to this census. ' +
  'lifehacker.dev lists 3 harnesses here and declares 17 lanes in its own fleet.manifest.yml.';

/** One AI workflow, as the census sees it. */
export interface RegistryHarness {
  workflow: string;
  path: string;
  /** `mention-handler`, `scheduled-agent`, … verbatim. */
  kind: string;
  /** The `*_ENABLED` repository variable, or `null` for an ungated harness. */
  switch: string | null;
  mentionHandler: boolean;
}

/** One repository's row. Only the fields the hub calls stable. */
export interface RegistryRepo {
  /** The hub's short name (its submodule directory when it has one). */
  repo: string;
  /** `owner/name`. */
  nwo: string;
  category: string;
  status: string;
  archived: boolean;
  scanned: boolean;
  /** Whether the repository commits a `fleet.manifest.yml`. */
  manifest: boolean;
  /** Whether GitFactory compiles workflows into it. */
  factory: boolean;
  /** `CLAUDE.md`, `AGENTS.md`, … or `null` when the census found none. */
  agentContext: string | null;
  /** `ok` | `missing` | `unknown`, verbatim. */
  oauthSecret: string;
  workflowsTotal: number | null;
  harnesses: RegistryHarness[];
  /** The census window's spend. `null` when the hub published none. */
  aiUsage: { runs: number | null; costUsd: number | null } | null;
  coverageOk: boolean | null;
  coverageMissing: string[];
}

export interface HarnessRegistry {
  schema: string;
  /** Verbatim from the file — the hub writes `2026-09-09 06:51 UTC`, not ISO. */
  generatedAt: string | null;
  repos: RegistryRepo[];
  blindSpotNote: string;
}

/** Exactly one of the two: a registry, or the reason there is none. */
export type ReadRegistryResult = HarnessRegistry | { refused: string };

/** Narrowing helper so callers do not have to test for a key. */
export function registryWasRefused(
  result: ReadRegistryResult,
): result is { refused: string } {
  return 'refused' in result;
}

// ---------------------------------------------------------------------------
// Coercion — the same posture as manifest.ts: coerce, never cast
// ---------------------------------------------------------------------------

function asRecord(value: unknown): Record<string, unknown> | undefined {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : undefined;
}

function asText(value: unknown): string {
  return value === undefined || value === null ? '' : String(value).trim();
}

function asTextOrNull(value: unknown): string | null {
  const text = asText(value);
  return text === '' ? null : text;
}

function asBool(value: unknown, fallback: boolean): boolean {
  if (typeof value === 'boolean') {
    return value;
  }
  const text = asText(value).toLowerCase();
  return text === 'true' ? true : text === 'false' ? false : fallback;
}

function asBoolOrNull(value: unknown): boolean | null {
  if (typeof value === 'boolean') {
    return value;
  }
  const text = asText(value).toLowerCase();
  return text === 'true' ? true : text === 'false' ? false : null;
}

function asNumberOrNull(value: unknown): number | null {
  if (typeof value === 'number' && Number.isFinite(value)) {
    return value;
  }
  const text = asText(value);
  if (text === '') {
    return null;
  }
  const parsed = Number(text);
  return Number.isFinite(parsed) ? parsed : null;
}

function asTextList(value: unknown): string[] {
  if (!Array.isArray(value)) {
    return [];
  }
  return value.map(asText).filter((entry) => entry !== '');
}

function coerceHarness(raw: unknown): RegistryHarness | undefined {
  const entry = asRecord(raw);
  if (entry === undefined) {
    return undefined;
  }
  const path = asText(entry.path);
  if (path === '') {
    return undefined;
  }
  return {
    workflow: asText(entry.workflow) || path,
    path,
    kind: asText(entry.kind) || 'unknown',
    switch: asTextOrNull(entry.switch),
    mentionHandler: asBool(entry.mention_handler, false),
  };
}

function coerceUsage(raw: unknown): RegistryRepo['aiUsage'] {
  const entry = asRecord(raw);
  if (entry === undefined) {
    return null;
  }
  return { runs: asNumberOrNull(entry.runs), costUsd: asNumberOrNull(entry.cost_usd) };
}

function coerceRepo(raw: unknown): RegistryRepo | undefined {
  const entry = asRecord(raw);
  if (entry === undefined) {
    return undefined;
  }
  const nwo = asText(entry.nwo);
  const repo = asText(entry.repo);
  if (nwo === '' && repo === '') {
    return undefined;
  }
  const coverage = asRecord(entry.coverage) ?? {};
  const harnesses = Array.isArray(entry.harnesses)
    ? entry.harnesses
        .map(coerceHarness)
        .filter((h): h is RegistryHarness => h !== undefined)
    : [];
  return {
    repo: repo || nwo,
    nwo: nwo || repo,
    category: asText(entry.category) || 'unknown',
    status: asText(entry.status) || 'unknown',
    archived: asBool(entry.archived, false),
    scanned: asBool(entry.scanned, false),
    manifest: asBool(entry.manifest, false),
    factory: asBool(entry.factory, false),
    agentContext: asTextOrNull(entry.agent_context),
    oauthSecret: asText(entry.oauth_secret) || 'unknown',
    workflowsTotal: asNumberOrNull(entry.workflows_total),
    harnesses,
    aiUsage: coerceUsage(entry.ai_usage),
    coverageOk: asBoolOrNull(coverage.ok),
    coverageMissing: asTextList(coverage.missing),
  };
}

/**
 * Read a `harness_registry.yml`. Never throws.
 *
 * A missing, empty, non-mapping or foreign-schema document comes back as
 * `{ refused }` with a sentence a person can act on. Everything else degrades
 * field by field: a repository row with neither `repo` nor `nwo` is dropped, a
 * harness with no `path` is dropped, a number that is not a number is `null`.
 */
export function readHarnessRegistry(text: string): ReadRegistryResult {
  const doc = asRecord(parseYamlSubset(text));
  if (doc === undefined) {
    return { refused: 'the harness registry is not a YAML mapping' };
  }
  const schema = asText(doc.schema);
  if (schema === '') {
    return { refused: 'the harness registry declares no schema' };
  }
  if (schema !== HARNESS_REGISTRY_SCHEMA) {
    return {
      refused: `schema "${schema}" is not ${HARNESS_REGISTRY_SCHEMA}`,
    };
  }
  const repos = Array.isArray(doc.repos)
    ? doc.repos.map(coerceRepo).filter((r): r is RegistryRepo => r !== undefined)
    : [];
  return {
    schema,
    generatedAt: asTextOrNull(doc.generated_at),
    repos,
    blindSpotNote: HARNESS_REGISTRY_BLIND_SPOT,
  };
}

/** The row for one `owner/name`, or `undefined`. Case-insensitive on the slug. */
export function registryRepoFor(
  registry: HarnessRegistry,
  slug: string,
): RegistryRepo | undefined {
  const wanted = slug.trim().toLowerCase();
  return registry.repos.find(
    (repo) => repo.nwo.toLowerCase() === wanted || repo.repo.toLowerCase() === wanted,
  );
}
